### ISSUE TITLE
hfkjwd

### ISSUE THREAD

**Issue by shiv-jetwal90** [phagunbaya/test-bot#4]
lfek

**Comment by phagunbaya** [comment]
Hey @shiv-jetwal90 you did not assigne these labels [size,type]

**Comment by phagunbaya** [comment]
Hey @shiv-jetwal90 you did not assigne these labels [size,type]

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
Hey @shiv-jetwal90 you did not assigne these labels [size]

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
@shiv-jetwal90 Please mention ready for review

**Comment by phagunbaya** [comment]
@Falkonry/qa The Issue is ready for Testing

**Comment by phagunbaya** [comment]
This Issue is ready for release
