### ISSUE TITLE
wfwf

### ISSUE THREAD

**Issue by shiv-jetwal90** [phagunbaya/test-bot#6]
qkflew

**Comment by phagunbaya** [comment]
Hey @shiv-jetwal90 you did not assigne these labels [size,type]

**Comment by phagunbaya** [comment]
Hey @shiv-jetwal90 you did not assigne these labels [size,assignee,type]

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.

**Comment by phagunbaya** [comment]
you have not completed task.
